### ISSUE TITLE
Search box should be empty at page load

### ISSUE THREAD

**Issue by alabulei1** [CyberMiles/smart_contracts#2]
When the user uses BACK button to go back to the search page, the search box should be empty.

搜索结果页面保留之前的搜索词，这个我觉得是对的，看完一个结果，我想去看另外一个结果。
如果我回到主页面就是想重新搜索新的词了

**Comment by Atlasoin** [comment]
Adding the clear search box when loading:
```
$(document).ready(function () {
    ...
    $(".search-box").val("")
}
```
