### ISSUE TITLE
blacklist

### ISSUE THREAD

**Issue by alabulei1** [CyberMiles/smart_contracts#3]
If the user knows a contract address that is on the blacklist, will he be able to search for it?

加入blacklist 只是首页不显示？
如果别人知道我的CMT 或者合约地址，能搜出来吗？

**Comment by juntao** [comment]
Let’s do this:

* latest: filtered by whitelist or blacklist
* search results: filtered by the whitelist or blacklist
* mine, won, participated: all results from ES

So if a user searches for an address on the blacklist, he will see no results.

**Comment by alabulei1** [comment]
Okay.

**Comment by Atlasoin** [comment]
Current structure:

- search results, promoted: filtered (blacklist + whitelist)
- mine, participated, won, all: unfiltered (blacklist)
